### ISSUE TITLE
Site fails with errors saying: Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain"...

### ISSUE THREAD

**Issue by d3adcom** [HalfdanJ/svelte-adapter-appengine#2]
"... Strict MIME type checking is enforced for module scripts per HTML spec."

When deploying files to App Engine with the help of this adapter, the javascript files that are uploaded to Google Cloud Storage (GCS) end up with the mime type text/plain (instead of "text/javascript" or perhaps "application/javascript"). This breaks my app and I can't figure out how to fix this, except by manually changing the metadata on every file within the corresponding GCS bucket. Any ideas?

**Comment by HalfdanJ** [comment]
Hmm interesting, i just double checked, and on the projects where I'm using the adapter, the files come through fine as `content-type: application/javascript`.  For example the file `start-xxxx.js`. 

- What os are you deploying from? 
- What browser are you using when accessing the deployed app? 
- Any chance you can share any steps/code with me? For example, is this happening also if you try and deploy the demo app from sveltekit?

**Comment by d3adcom** [comment]
Ok, I just tried again with a newly initialized Sveltekit demo app. I'm using Windows 10 with VSCode and my browser is Google Chrome.

During install, I picked Typsecript and chose yes to ESLint and Prettier. Ran "npm install" and after that, I ran "npm install --save-dev svelte-adapter-appengine", followed by adding the adapter into the svelte.config.js. 

When I tried to run "gcloud app deploy --project [my-project] .appengine_build_output/app.yaml", it failed with this error before deploying: 

`Do you want to continue (Y/n)?  y

Created .gcloudignore file. See `gcloud topic gcloudignore` for details.
#============================================================#
#= Uploading 27 files to Google Cloud Storage               =#
#============================================================#
File upload done.
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: The request is invalid.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: 'Value "static\about\index.html" must be a valid regular expression.
      Details: invalid escape sequence.'
    field: version.handlers[1].static_files.upload_path_regex
  - description: 'Value "static\index.html" must be a valid regular expression. Details:
      invalid escape sequence.'
    field: version.handlers[3].static_files.upload_path_regex`

Note: this is the first time seeing this error. I didn't get this error with my own app. 

In order to get past this error, I edited the app.yaml file to use forward slashes instead of backslashes (just a guess and it seemed to work).

Deployed again and the deploy succeeded this time, except when I navigate to the site, I am receiving the same error as I did with my own app where it says [in the console]: 

`start-fb601285.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
vendor-836cc791.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
__layout.svelte-58ad4c91.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
index.svelte-eaf55abf.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.`

The page loads, but the active elements don't work. I can't adjust the counter or add any todos. This is the URL to the website, if you are interested in checking it out on your end: https://canflight.wl.r.appspot.com/

**Comment by d3adcom** [comment]
In the top comment, I mentioned that changing the content type manually on the objects in the GCS bucket might work, but I actually tried that last night and it doesn't work :( For now, I managed to get my app loaded up on Vercel without any errors, so I will just use that instead for the time being.

**Comment by HalfdanJ** [comment]
Thanks a lot for the details. I'll boot up my windows computer later and try to replicate it there. I had only tested this on Mac.

**Comment by HalfdanJ** [comment]
Ok, i've released a 0.1.1 version that fixes the  \ vs / issue in app.yaml. But I have not been able to reproduce your larger issue around mimetype. 

I did exactly what you did on my windows machine, created a sveltekit app, added the adapter, build it and deployed it (to here: https://svelte-demo-329602.uc.r.appspot.com/), and its working just as expected. Does this deployed version work for you? 

My app.yaml looks like this now, generated on windows: 

```
runtime: nodejs16
entrypoint: node index.js
handlers:
  - url: /_app
    static_dir: client/_app
  - url: /about/
    static_files: static/about/index.html
    upload: static/about/index.html
  - url: /favicon.png
    static_files: static/favicon.png
    upload: static/favicon.png
  - url: /
    static_files: static/index.html
    upload: static/index.html
  - url: /robots.txt
    static_files: static/robots.txt
    upload: static/robots.txt
  - url: /svelte-welcome.png
    static_files: static/svelte-welcome.png
    upload: static/svelte-welcome.png
  - url: /svelte-welcome.webp
    static_files: static/svelte-welcome.webp
    upload: static/svelte-welcome.webp
  - url: /.*
    secure: always
    script: auto
```
