### ISSUE TITLE
No way to configure login for built in routes?

### ISSUE THREAD

**Issue by hovavo** [HalfdanJ/svelte-adapter-appengine#208]
I might be missing something but I can't find a way to configure the built in routes (e.g. to require login with `login: required`).

The merged app.yaml method seem to only be able to add extra handlers and doesn't allow modifying or overriding the built in ones.
Also, it adds the extra handlers before the built in ones so event adding my own won't override them.

Any ideas?

**Comment by HalfdanJ** [comment]
You are right that i've never considered this need, just never had a need for it myself. In order to do this, i think a new parameter will have to be added to the config object that allows specifying which paths should have that set. Hmmm

**Comment by HalfdanJ** [comment]
Thinking more about it, i think it makes sense to move the custom handlers to the end, that way you can accomplish it by just overwriting the routes you want. Like this: #221 

Would that work for your usecase?

**Comment by hovavo** [comment]
Thanks! Yeah looks like it solves my use case.
One thing though is that the output app.yaml may look odd with duplicate routes.
I guess a commented explanation before the overrides can solve that.   

Another approach I was thinking of is merging the overrides into the matching routes. I reckon it's a bigger change to implement though.

**Comment by HalfdanJ** [comment]
It wont be a duplicate entry in most cases, most routes are captured by 

```
  - url: /.*
    secure: always
    script: auto
```

**Comment by hovavo** [comment]
Well I'm embarrassed to say that after another test deploy it looks like I was wrong all along, and my use case is actually already supported as is. Unfortunately I can't recall how I first tested it and came to the conclusion it isn't :/

This following app.yaml does work in the sense that all routes require admin login thanks to the custom `/.*` route added in the beginning, and the closing duplicate route doesn't change that.
Sorry for the false alarm!

```
service: default
env: standard
runtime: nodejs18
handlers:
  - url: /.*
    secure: always
    script: auto
    login: admin
  - url: /favicon.ico
    static_files: storage/favicon.ico
    upload: storage/favicon.ico
    secure: always
  - url: /favicon.png
    static_files: storage/favicon.png
    upload: storage/favicon.png
    secure: always
  - url: /_app/immutable/
    static_dir: storage/_app/immutable
    expiration: 30d 0h
    secure: always
  - url: /_app/
    static_dir: storage/_app
    secure: always
  - url: /.*
    secure: always
    script: auto
```
