### ISSUE TITLE
Invalid runtime

### ISSUE THREAD

**Issue by Lootwig** [HalfdanJ/svelte-adapter-appengine#51]
After successful file upload, the `gcloud app deploy` step exits with the following error:

```
ERROR: (gcloud.app.deploy) Error Response: [3] "runtime: nodejs16" does not exist.
```

After checking the configuration of previous deployments using the "node" adapter, I can see that their runtime name was simply "nodejs".
Is any configuration inside gcloud required in order to use the specified "nodejs16" value generated into the app.yaml?

**Comment by HalfdanJ** [comment]
It should according to documentation be `nodejs16` https://cloud.google.com/appengine/docs/standard/nodejs/runtime 
Can you see if you have an update to `gcloud`?

**Comment by Lootwig** [comment]
Yeah, I've seen that doc and it makes the error seem pretty weird.

There was an update for gcloud, but after running it the error is still the same.

Output of `glcoud version`:

```
Google Cloud SDK 402.0.0
bq 2.0.75
core 2022.09.12
gsutil 5.13
```

Which versions are you on for these?

**Comment by HalfdanJ** [comment]
Oh thats so weird. I'm the same now, no issues. 

Can you share your full app.yaml file from build folder?

**Comment by Lootwig** [comment]
```yaml
runtime: nodejs16
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
entrypoint: node index.js
handlers:
  - url: /_app/immutable/
    static_dir: storage/_app/immutable
    expiration: 30d 0h
  - url: /_app/
    static_dir: storage/_app
  - url: /.*
    secure: always
    script: auto
```
