### ISSUE TITLE
Pre-rendered server-side routes don't have handlers generated for them.

### ISSUE THREAD

**Issue by infovore** [HalfdanJ/svelte-adapter-appengine#62]
I have an endpoint (`src/routes/foo/[...slug].json/+server.ts`) that I prerender (for $reasons), by passing the paths into the list of paths to prerender in `svelte.config.js`, and adding `export const prerender = true` to the endpoint file.

This correctly outputs a pile of files as `build/storage/foo/**/*.json`. However! It does _not_ add those entries to the configured `app.yaml`, meaning they don't get uploaded/handled correctly by GAE.

I think this might be also generating entries for items in `builder.prerendered.paths`... but haven't had the time to look into this just yet.

**Comment by infovore** [comment]
The current workaround is to make a handler manually, in `/app.yaml`, which will get merged into the generated file later:

```yaml
handlers:
- url: /foo/(.*\.json)$
  static_files: storage/foo/\1
  upload: storage/foo/.*\.json$
```
